using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    private static GameManager _instance;

    public static GameManager Instance { get { return _instance; } }

    // Start is called before the first frame update
   void Awake(){
        DontDestroyOnLoad (transform.gameObject);

        if (_instance != null && _instance != this)
        {
            Destroy(this.gameObject);
        } else {
            _instance = this;
        }    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
